### ISSUE TITLE
Error: You must specify options.format

### ISSUE THREAD

**Issue by iMilad** [pvdlg/karma-rollup-preprocessor#35]
Hey,
Sure the configuration is working properly, because the "Standard" config gives me an error: 
`[!] Error: You must specify options.format, which can be one of 'amd', 'cjs', 'es', 'iife' or 'umd' `

Karma.conf.js

```
const babel = require('rollup-plugin-babel');

module.exports = function(config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine'],

    files: [
      'test/bundle.js',
    ],

    exclude: [
    ],

    preprocessors: {
      '**/*.js': ['rollup']
    },

    rollupPreprocessor: {
        options: {
          output: {
              sourceMaps: true,
              format: 'iife'
          },
            plugins: [babel({presets: [['es2015', {modules: false}]]})],
        },
        transformPath: filePath => filePath.replace('src/js', 'script')
    },

    reporters: ['progress'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_DEBUG,
    autoWatch: false,
    browsers: ['Chrome'],
    singleRun: true,
    concurrency: Infinity
  })
}
```

**Comment by vanduynslagerp** [comment]
Thanks for the report !

Are you using the version `3.0.0` of this package? Only `rollup` >= `0.48` is supported as it contains changes in the way to `format` is configured.

Can you check which version you are using ? You be using an older version due to package-lock.json or `.yarn.lock`.

Do you you have a repo with configuration? So it will easier for me to reproduce.

**Comment by vanduynslagerp** [comment]
Actually, looking at it again, you are not using this plugin.
You have to add it to your config:
```js
plugins: ['@metahub/karma-rollup-preprocessor', 'karma-*']
```
